#!/bin/sh

set -e

ENVIRONMENT=`grep environment shared/app.properties | sed -e 's/environment=\(.*\)$/\1/'`

UPCOMING_DATE=`date +%Y%m%d%H%M%S`
UPCOMING_NAME=dev
UPCOMING_FULL="$UPCOMING_DATE-$UPCOMING_NAME"

cd releases/dev

echo " > version $UPCOMING_NAME"
echo " > deploy $UPCOMING_FULL"

/bin/sh <<EOF
    cd deploy/boot/puppet
    librarian-puppet install
    /usr/bin/puppet apply \
        --environment=$ENVIRONMENT \
        --modulepath=modules \
        -e '\$app = merge(loadyaml("$PWD/../../private/app.yaml"), { deploy => { path => "$PWD", name => "$UPCOMING_NAME", date => "$UPCOMING_DATE" } }) include app::deploy'
EOF

ant -Dapp.deploy.date="$UPCOMING_DATE" -Dapp.deploy.name="$UPCOMING_NAME" -Dapp.deploy.full="$UPCOMING_FULL" prepare

cd ../../

if [[ -f current ]]; then
    cd current/
    ant undeploy
    
    cd ../
    unlink current
fi

ln -s releases/$UPCOMING_FULL current

cd releases/$UPCOMING_FULL

ant -Dapp.deploy.date="$UPCOMING_DATE" -Dapp.deploy.name="$UPCOMING_NAME" -Dapp.deploy.full="$UPCOMING_FULL" deploy
