#!/bin/sh

set -e

INSTALL_DIR=$PWD
ENVIRONMENT=`grep environment shared/app.properties | sed -e 's/environment=\(.*\)$/\1/'`

UPCOMING_DATE=`date +%Y%m%d%H%M%S`
UPCOMING_NAME=dev
UPCOMING_FULL="$UPCOMING_DATE-$UPCOMING_NAME"

cd releases/dev
ln -s $INSTALL_DIR/shared mnt

echo " > version $UPCOMING_NAME"
echo " > deploy $UPCOMING_FULL"

/bin/sh <<EOF
    cd deploy/boot/puppet
    librarian-puppet install
    /usr/bin/puppet apply \
        --environment=$ENVIRONMENT \
        --modulepath=modules \
        -e '\$app = merge(loadyaml("$INSTALL_DIR/private/app.yaml"), { deploy => { path => "$PWD", name => "$UPCOMING_NAME", date => "$UPCOMING_DATE" } }) include app::deploy'
EOF

ant -Dapp.deploy.date="$UPCOMING_DATE" -Dapp.deploy.name="$UPCOMING_NAME" -Dapp.deploy.full="$UPCOMING_FULL" prepare

cd ../../

if [[ -s current ]]; then
    cd current/
    ant undeploy
    
    cd ../
    unlink current
fi

ln -s releases/dev current

cd releases/dev

ant -Dapp.deploy.date="$UPCOMING_DATE" -Dapp.deploy.name="$UPCOMING_NAME" -Dapp.deploy.full="$UPCOMING_FULL" deploy
